# See: https://mise.jdx.dev/tasks/toml-tasks.html

[tools]
markdownlint-cli2 = "latest"
lefthook = "latest"
uv = "latest"

[tasks.setup]
description = "Setup tools"
run = ["uv python install", "uv sync", "lefthook install"]
alias = "s"

[tasks.link]
description = "Create a symbolic link to your each Claude directory."
usage = '''
arg "<claude_home>" help="Path to your Claude home directory." default="~/.claude"
'''
run = ["ln -sfn $(pwd)/skills ${usage_claude_home}/skills"]

[tasks.fix-md]
description = "Fix markdown"
run = ["markdownlint-cli2 '**/*.md' --fix"]
alias = "fm"

[tasks.check-md]
description = "Check markdown"
run = ["markdownlint-cli2 '**/*.md'"]
alias = "cm"
